FROM nvcr.io/nvidia/tensorrt:23.01-py3

WORKDIR /app

ADD https://web.lcrc.anl.gov/public/waggle/models/ptychonn/ptychoNN_8_128_fp16.trt /app/model_128.trt
ADD https://web.lcrc.anl.gov/public/waggle/models/ptychonn/ptychonn_512_bsz8_fp32.trt /app/model_512_fp32.trt
ADD https://web.lcrc.anl.gov/public/waggle/models/ptychonn/ptychonn_512_bsz8_fp16.trt /app/model_512_fp16.trt
ADD https://web.lcrc.anl.gov/public/waggle/models/ptychonn/diff_scan_810.npy /app/scan.npy

COPY requirements.txt /app
RUN pip3 install --upgrade pip
RUN pip3 install -r requirements.txt

COPY inferPtychoNN.py inferPtychoNNImageProcessor.py helper.py /app/
ENV PYTHONPATH "${PYTHONPATH}:/app"
EXPOSE 9100