---
- name: Demo Playbook for Streaming
  hosts: localhost
  gather_facts: false
  connection: local

  vars:
    demo_item_count: "{{ demo_item_count | default(15) | int }}"
    sleep_interval: "{{ sleep_interval | default(2) | int }}"

  tasks:
    - name: Start demo job
      debug:
        msg: "🚀 Starting demo Ansible job..."

    - name: Process demo items
      debug:
        msg: "📊 Processing demo item {{ item }}/{{ demo_item_count }} - {{ ansible_date_time.time }}"
      loop: "{{ range(1, demo_item_count + 1) | list }}"

    - name: Show checkpoint
      debug:
        msg: "⚡ Checkpoint reached at item {{ item }}"
      loop: "{{ range(1, demo_item_count + 1) | list }}"
      when: item % 5 == 0

    - name: Wait between items
      pause:
        seconds: "{{ sleep_interval }}"
      loop: "{{ range(1, demo_item_count + 1) | list }}"

    - name: Complete demo job
      debug:
        msg: "✅ Demo Ansible job completed successfully!"
