apiVersion: v1
kind: Pod
metadata:
  name: sim-server
spec:
  restartPolicy: Never
  containers:
  - name: sim-server
    resizePolicy: # for pod being updated without restarting
    - resourceName: cpu
      restartPolicy: NotRequired
    - resourceName: memory
      restartPolicy: NotRequired
    image: gemblerz/ptychonn:0.1.4
    command: ["pvapy-ad-sim-server"]
    args:
    - --channel-name
    - ad:image
    - --n-x-pixels
    - "512"
    - --n-y-pixels
    - "512"
    - --datatype
    - int16
    - --frame-rate
    - "100"
    - --runtime
    - "60"
    - --disable-curses
    resources:
      limits:
        memory: 3Gi
      requests:
        cpu: 1000m
        memory: 500Mi
